#!/usr/bin/python3

from urllib.request import urlopen
from urllib.parse import quote
import os
import sys
import json
import socket
import ipaddress

cfg = "/etc/ssh-notify.conf.json"
if len(sys.argv) > 1:
	cfg = sys.argv[1]

if "-h" in sys.argv or "--help" in sys.argv:
	print("Usage: %s [path to configuration file]" % sys.argv[0])
	sys.exit(1)

rhost = os.getenv("PAM_RHOST")
user = os.getenv("PAM_USER")
config = json.loads(open(cfg).read())

if user in config.get('ignored-users', []):
	sys.exit(0)

ignored_hosts = config.get('ignored-hosts', [])
if ignored_hosts:
	rhost_addr = socket.gethostbyname(rhost)
	for ignored_host in ignored_hosts:
		if ignored_host in (rhost, rhost_addr):
			sys.exit(0)
		if ipaddress.ip_address(rhost_addr) in ipaddress.ip_network(ignored_host):
			sys.exit(0)

msg = "Login for %s from %s on %s" % (user, rhost, socket.gethostname())

for device in config.get('devices'):
	params = {
			"action": "push_public_outbound_message_send",
			"api_key": config['api_key'],
			"message": msg,
			"device_id": device,
	}

	if config.get('thread'):
		params['thread_id'] = config.get('thread')

	if os.getenv("PAM_TYPE") == "open_session":
		url = "https://push.panaceamobile.com/?" + "&".join("%s=%s" % (quote(k), quote(v)) for k,v in params.items())
		urlopen(url).read()
